language: php

php:
  - 5.3
  - 5.2

before_script:
  - git clone git://github.com/cakephp/cakephp ../cakephp
  - cd ..
  - mv cakephp-viewed cakephp/app/Plugin/Viewed
  - chmod -R 777 cakephp/app/tmp
  - sh -c "mysql -e 'CREATE DATABASE turnera;'"
  - echo "<?php
   class DATABASE_CONFIG {
   public \$default = array(
     'datasource' => 'Database/Mysql',
     'database' => 'turnera',
     'host' => '0.0.0.0',
     'login' => 'travis',
     'prefix' => '',
     'persistent' => false,
   );
   public \$test = array(
     'datasource' => 'Database/Mysql',
     'database' => 'turnera',
     'host' => '0.0.0.0',
     'login' => 'travis',
     'prefix' => '',
     'persistent' => false,
   );
   }" > cakephp/app/Config/database.php
  - sh -c "./cakephp/app/Console/cake schema create --plugin Viewed --file schema.php << EOF
           n
           y
           EOF";
  - echo "CakePlugin::load( 'Viewed' ); " >> cakephp/app/Config/bootstrap.php
  - echo "Configure::write('Security.salt', 'DYhG93b0qyJtfIxufs2gruVoUubWnwvniRe2G0FraCa9mi');" >> cakephp/app/Config/core.php
  - echo "Configure::write('Security.cipherSeed', '7685923096357445354624962749683645');" >> cakephp/app/Config/core.php

script:
  - ./cakephp/app/Console/cake test Viewed AllTests --stderr