language: php

php:
  - 5.3

before_script:
  - git clone git://github.com/cakephp/cakephp ../cakephp
  - cd ..
  - mv cakephp-viewed cakephp/app/Plugin/Viewed
  - chmod -R 777 cakephp/app/tmp
  - echo "<?php
   class DATABASE_CONFIG {
   public \$default = array(
     'datasource' => 'Database/Mysql',
     'database' => 'test',
     'host' => '0.0.0.0',
     'login' => 'travis',
     'prefix' => '',
     'persistent' => false,
   );
   public \$test = array(
     'datasource' => 'Database/Mysql',
     'database' => 'test',
     'host' => '0.0.0.0',
     'login' => 'travis',
     'prefix' => 'test_',
     'persistent' => false,
   );
   }" > cakephp/app/Config/database.php
  - sh -c "mysql < cakephp/app/Plugin/Viewed/Config/Schema/schema.sql"
  - echo "CakePlugin::load( 'Viewed' ); " >> cakephp/app/Config/bootstrap.php
  - echo "Configure::write('Security.salt', 'DYhG93b0qyJtfIxufs2gruVoUubWnwvniRe2G0FraCa9mi');" >> cakephp/app/Config/core.php
  - echo "Configure::write('Security.cipherSeed', '7685923096357445354624962749683645');" >> cakephp/app/Config/core.php
  - cp cakephp/app/Plugin/Viewed/composer.json composer.json
  - composer install --dev
  - mkdir -p build/logs

script:
  - ./cakephp/app/Console/cake test Viewed Model/Behavior/ViewedBehavior --stderr --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls